development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: martian_library-db_development
  pool: 5
  username: postgres
  password:
  port: 5433

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: martian_library-db_test
  pool: 5
  username: postgres
  password:
  port: 5433
